/**
 *
 * 图片360旋转
 * 详细用法请参考：http://v3.spice.lh/javascript/drag360
 * 如果链接无法访问，请联系QQ：1515110755 或 RTX：hong.liang
 *
 * @ author Razy
 * @ version 1.0
 *
 */
!function(a,b,c){"object"==typeof module&&"object"==typeof module.exports?module.exports=b(a):a.spice.drag360=b(a)}(jQuery,function(a){function b(b,c){if(!b||a.isPlainObject(b))return!1;var d=[];return a(b).each(function(b,f){var g=a(f),h=g.data("spice.drag360");h||g.data("spice.drag360",h=new e(g,c)),d.push(h)}),d}var c={imgSrc:"/docs/images/360/surface%i%.jpg",imgNum:36,scale:10,animate:!1,speed:70,callBack:null},d={namespace:".drag360",loadImg:function(b){for(var c=b.opt.imgNum,e=b.opt.imgSrc,f=[],g=1;g<=c;g++)f.push(e.replace("%i%",g));a.when.apply(a,a(f).map(function(d,e){if(e){var f=a.Deferred(),g=new Image;return g.onload=function(){f.resolve();var d=b.elem.data("data-in-load");d?++d:d=1,b.elem.data("data-in-load",d),b.opt.callBack&&a.isFunction(b.opt.callBack)&&b.opt.callBack(Math.ceil(100*d/c)+"%")},g.src=e,f.promise()}return!0})).done(function(){0!=a("img.drag-loading",b.elem).length?(a("img.drag-loading",b.elem).fadeOut("slow"),a("img.drag-image",b.elem).fadeIn("slow",function(){setTimeout(function(){d.scrollHover(b),d.animate(b)},400)})):(d.scrollHover(b),d.animate(b))})},setImgSrc:function(b,c){a("img.drag-image",b.elem).attr("src",b.opt.imgSrc.replace("%i%",c))},animate:function(b){var c=b.opt,e=b.elem.attr("data-current")||0;++e,b.elem.attr("data-current",e),d.setImgSrc(b,e);var f=c.animate,g=c.speed;f&&g&&a.isNumeric(g)&&(b.elem.data("spice.drag360.animate",!0),e>c.imgNum?(b.elem.attr("data-current",1),d.setImgSrc(b,1),b.elem.data("spice.drag360.animate",!1)):setTimeout(function(){d.animate(b)},g))},sx:0,mx:0,scrollHover:function(b){var c=a.spice.mousemove+d.namespace,e=a.spice.mouseup+d.namespace,f=a.spice.mousedown+d.namespace;a("body,html").on(f,function(f){var g=a(this);if(b.elem.data("spice.drag360.animate"))return!1;if(a.contains(b.elem[0],f.target))if(a.spice.hasTouch||f.preventDefault(),a(f.target).hasClass("btn")||0!=a(f.target).closest(".btn").length){var h=a(f.target).hasClass("btn")?a(f.target):a(f.target).closest(".btn"),i=b.opt,j=i.speed,k=null;j&&a.isNumeric(j)&&(k=setInterval(function(){var a=b.elem.attr("data-current")||0;h.hasClass("btn-drag-next")?++a>i.imgNum&&(a=1):--a<=0&&(a=i.imgNum),b.elem.attr("data-current",a),d.setImgSrc(b,a)},j)),g.off(e).on(e,function(a){k&&clearInterval(k)})}else{var l=a.spice.getEventXY(f),m=0;d.sx=l.x,d.mx=0,g.on(c,function(c){var e=a.spice.getEventXY(c);d.mx=e.x,Math.abs(d.mx-d.sx)>8&&c.preventDefault();var f=(d.mx-d.sx)/b.opt.scale;m=parseInt((+b.elem.attr("data-current")+f+Math.abs(Math.floor(f/b.opt.imgNum))*b.opt.imgNum)%b.opt.imgNum)+1,d.setImgSrc(b,m)}).on(e,function(a){g.off(c).off(e),b.elem.attr("data-current",m)})}})}},e=function(b,d){var e=this;e.opt=a.extend({},c,d),e.elem=b,e.init()};return e.prototype={init:function(){d.loadImg(this)},destroy:function(){this.elem.removeData("data-in-load"),d.setImgSrc(this,1),a("body,html").off(a.spice.mousedown+d.namespace)}},b});